#!/usr/bin/env bash

# To run this script enter "./deploy" in your terminal from 
# the root directory without the quotes

echo "NOTE: Don't forget to merge your changes into master before deploying"

git checkout master &&
rm -rf dist &&
cd ../frontend  &&
npm run build &&
cd .. &&
cp -r frontend/dist backend &&
git add . &&
git commit -m "updates build for deployment" &&
git subtree push --prefix backend heroku master 
