export const UPDATE_MODULE_STATE = 'UPDATE_MODULE_STATE';
const FETCH_MODULES_FAILURE = 'FETCH_MODULES_FAILURE';
const FETCH_MODULES_SUCCESS = 'FETCH_MODULES_SUCCESS';
const FETCH_MODULES_REQUEST = 'FETCH_MODULES_REQUEST';
const UPDATE_SELECTED_MODULE = 'UPDATE_SELECTED_MODULE';
export const LOAD_REACTIONS = 'LOAD_REACTIONS';
export const LOAD_MODULES = 'LOAD_MODULES';
export const FETCH_MODULES = 'FETCH_MODULES';
