export const HANDLE_UPDATE_STATE_MESSAGE = 'HANDLE_UPDATE_STATE_MESSAGE';
export const UPDATE_MODULE_STATE = 'UPDATE_MODULE_STATE';
export const UPDATE_MODULE_PARAMS = 'UPDATE_MODULE_PARAMS';
export const UPDATE_MODULE_LIMITS = 'UPDATE_MODULE_LIMITS';
export const LOAD_REACTIONS = 'LOAD_REACTIONS';
export const LOAD_MODULES = 'LOAD_MODULES';
export const FETCH_MODULES = 'FETCH_MODULES';
