// Modules types
export const FETCH_MODULES_FAILURE = 'FETCH_MODULES_FAILURE';
export const FETCH_MODULES_SUCCESS = 'FETCH_MODULES_SUCCESS';
export const FETCH_MODULES_REQUEST = 'FETCH_MODULES_REQUEST';
export const UPDATE_SELECTED_MODULE = 'UPDATE_SELECTED_MODULE';

// Entity types
export const FETCH_MODULES = 'FETCH_MODULES';
export const LOAD_MODULES = 'LOAD_MODULES';
export const LOAD_REACTIONS = 'LOAD_REACTIONS';
export const SET_HEATER_LEVEL = 'SET_HEATER_LEVEL';
export const UPDATE_MODULE_STATE = 'UPDATE_MODULE_STATE';

// UI types
export const SET_AIR_ACTIVE = 'SET_AIR_ACTIVE';
export const SET_LIGHT_ACTIVE = 'SET_LIGHT_ACTIVE';
export const SET_HEATER_ACTIVE = 'SET_HEATER_ACTIVE';
